name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: ✅ Lint packages
        run: pnpm run -w lint

      - name: 👷 Build packages
        run: pnpm run -w build

      - name: 🧪 Test packages
        run: pnpm run -w test
